version: '3.9'

services:
  wiremock:
    image: wiremock/wiremock:2.35.0
    ports:
      - 8080:8080
    volumes:
      - ./Wiremock/Stubs:/home/wiremock/mappings
    command: --verbose --global-response-templating --root-dir /home/wiremock
    networks:
      - dynamo-network


networks:
  dynamo-network: